<?php
/**
 * @var PhpRenderer $this
 * @var ElementInterface $element
 * @var string $label
 * @var array $labelAttributes
 * @var string $labelPosition
 * @var bool $renderErrors
 */

use Laminas\Form\ElementInterface;
use Laminas\View\Renderer\PhpRenderer;

?>
<div class="form-row checkbox">
    <div class="inputs">
        <?= $this->formLabel()->openTag($element) ?>
        <?= $this->formCheckbox($element) ?>
        <?= $label ?>
        <?= $this->formLabel()->closeTag($element) ?>
    </div>
    <?php if ($renderErrors): ?>
        <?= $this->formElementErrors($element, ['class' => 'error']) ?>
    <?php endif ?>
</div>
