<?php
/**
 * @var PhpRenderer $this
 * @var ElementInterface $element
 * @var string $label
 * @var array $labelAttributes
 * @var string $labelPosition
 * @var bool $renderErrors
 */

use Laminas\Form\ElementInterface;
use Laminas\View\Renderer\PhpRenderer;

?>
<div class="form-row">
    <?php if ($element->getLabel()): ?>
        <?= $this->formLabel($element) ?>
    <?php endif ?>
    <div class="inputs">
        <?= $this->formFile($element) ?>
    </div>
    <?php if ($renderErrors): ?>
        <?= $this->formElementErrors($element, ['class' => 'error']) ?>
    <?php endif ?>
</div>
